all:
	g++ -fopenmp -std=c++11 -O3 -I../../../software/include/fastxio -I../../../software/fastxio/generic_matrix -L../../../software/lib -o contaminant_filter contaminant_filter.cpp /sw/apps/build/boost/1.63.0_gcc6.3.0/rackham/lib/libboost_program_options.so.1.63.0 -lfastxio
